baseurl = "https://studiozenkai.com"
languageCode = "en-us"
title = "Studio Zenkai"
twitter = "heri"
github = "heri"
flickr = "heri_quebec"
facebook = "heri.rakotomalala"
linkedin = "madmedia"
email = "heri@studiozenkai.com"
theme = "hugo-uno"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  author = "Heri Rakotomalala"
  Subtitle = "Software, photography, and sustainability articles by Heri"
  description = "Studio Zenkai is dedicated to the craft of programming, photography and living sustainably."
  math = true
  cusdis = true