/* 2675 boul. Poirier: building duty calendar.
   Reads schedule.json (generated by tools/generate.py). No dependencies.
   Bilingual: UI strings live in STR below; job and bin texts come from schedule.json. */
(function () {
  "use strict";

  // ---------- UI strings ----------
  var STR = {
    en: {
      locale: "en-CA",
      docTitle: "2675 boul. Poirier · Building duty calendar",
      title: "2675 boul. Poirier",
      subtitle: "Building duty calendar · 4 jobs, 4 units, every 2 weeks · 2 units off",
      prev: "Previous month", next: "Next month",
      rule: "Bins go to the curb at 7pm the evening before pickup and come back in at 7pm on pickup day.",
      legend: { compost: "Compost (pickup every Tuesday)", recycling: "Recycling: each unit, own bin (Tuesday)", garbage: "Garbage (every other Friday)" },
      legendBins: "Day colour = unit on bins duty",
      weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      bins: "Bins", unit: "Unit", all: "All", at7: "7pm:", at7long: "7pm",
      short: { out: "Out", back: "Back" },
      agendaTitle: function (m) { return "Bin actions in " + m; },
      whoTitle: "Who does what", period: "Period",
      printLink: function (m) { return "Printable calendar for " + m + " (PDF)"; },
      nowToday: "Tonight at 7pm", nowNext: "Next bin action", nowOnDuty: "On bins duty now",
      nowStarts: function (d) { return "The rotation starts on " + d + "."; },
      mineTitle: "My unit", pick: "Choose your unit", pickNone: "Select…",
      mineIntro: function (u, a, b) { return "Unit " + u + "'s jobs from " + a + " to " + b + "."; },
      weekly: "Every week", weeklyNext: function (d) { return "Next: " + d + ", 7pm."; },
      off: "Off", offText: "No job this period. Enjoy!",
      done: "done", current: "now",
      binActions: "Your 7pm bin actions",
      subTitle: "Add to your calendar",
      subIntro: "Your unit's jobs and 7pm bin reminders (including your recycling), updated every month.",
      subApple: "Subscribe on iPhone / Mac", subAppleHint: "Opens Apple Calendar (one tap).",
      subUrl: "Calendar link", copy: "Copy link", copied: "Copied",
      subGoogle: "<b>Google Calendar</b> (on a computer): Other calendars <b>+</b> → <b>From URL</b> → paste the link. It then shows on your Android phone too.",
      subOutlook: "<b>Outlook</b>: Add calendar → <b>Subscribe from web</b> → paste the link.",
      subNote: "Google may take up to a day to refresh subscribed calendars.",
      faqTitle: "Questions",
      faq: [
        ["Can't do your job?",
         "<p>Swap with another unit, then write the swap on the printed calendar in the entrance. That's it.</p>"],
        ["Who takes out the recycling?",
         "<p>Each unit has its own recycling bin, so <b>every unit</b> puts its own bin out Monday at 7pm and brings it back in Tuesday at 7pm, every week. The unit on bins duty only handles the shared <b>compost</b> and <b>garbage</b> bins.</p>"],
        ["What exactly does each job involve?", "JOBS"],
        ["I'm a tenant. Does this apply to me?",
         "<p>Yes. Every unit is responsible when it's assigned, whether the work is done by the tenant or the owner. Tenants: check with your unit's owner. Owners stay responsible for making sure their unit's job gets done.</p>"],
        ["Why do we need to do all this?",
         "<p>We have a company for major work such as snow plowing the driveway or renovating the basement. To keep costs down, it's our collective duty to take care of the small things. Everyone participates; otherwise a management firm will be brought in, and that raises everyone's costs.</p>"],
        ["What are the collection rules?",
         "<ul><li>Bins may only be at the curb from <b>7pm the evening before</b> pickup to <b>7am on pickup day</b> (city rule).</li>" +
         "<li>Bring bins back in at <b>7pm on pickup day</b> (building rule).</li>" +
         "<li>Compost and recycling: every Tuesday. Garbage: every other Friday (Saint-Laurent, sector 1).</li>" +
         "<li>Leaves go in <b>paper bags or reusable containers</b>, out with the compost. No plastic bags, even compostable ones.</li>" +
         "<li>Large items (1st Friday of the month) aren't part of the rotation: each owner handles their own.</li>" +
         "<li>Holidays can move a pickup. Check <a href=\"https://montreal.ca/info-collectes\" rel=\"noopener\">Info-Collecte</a> or call 311.</li></ul>"],
        ["Where's the printed calendar?", "PRINT"]
      ],
      majorWork: "Major work (snow plowing the driveway, basement renovation…) is done by a hired company and isn't part of the rotation.",
      seasons: { all: "All year", fall: "Fall (Oct–Nov)", winter: "Winter (Dec–Mar)", spring_summer: "Spring & summer (Apr–Sep)" },
      printList: "This month's printout is posted in the entrance. PDFs:",
      foot: function (d) { return "Updated " + d + ". Questions or a swap to record? Post in the building WhatsApp group."; },
      loadError: "Couldn't load the calendar. Please reload the page."
    },
    fr: {
      locale: "fr-CA",
      docTitle: "2675 boul. Poirier · Calendrier des tâches",
      title: "2675 boul. Poirier",
      subtitle: "Calendrier des tâches · 4 tâches, 4 unités, aux 2 semaines · 2 unités en congé",
      prev: "Mois précédent", next: "Mois suivant",
      rule: "Les bacs vont au bord de la rue à 19 h la veille de la collecte et sont rentrés à 19 h le jour de la collecte.",
      legend: { compost: "Bac brun / compost (chaque mardi)", recycling: "Recyclage : chaque unité, son bac (mardi)", garbage: "Ordures (un vendredi sur deux)" },
      legendBins: "Couleur du jour = unité de service aux bacs",
      weekdays: ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"],
      bins: "Bacs", unit: "Unité", all: "Tous", at7: "19 h :", at7long: "19 h",
      short: { out: "Sortir", back: "Rentrer" },
      agendaTitle: function (m) { return "Bacs en " + m.toLowerCase(); },
      whoTitle: "Qui fait quoi", period: "Période",
      printLink: function (m) { return "Calendrier imprimable de " + m.toLowerCase() + " (PDF)"; },
      nowToday: "Ce soir à 19 h", nowNext: "Prochaine sortie des bacs", nowOnDuty: "De service aux bacs",
      nowStarts: function (d) { return "La rotation commence le " + d + "."; },
      mineTitle: "Mon unité", pick: "Choisissez votre unité", pickNone: "Choisir…",
      mineIntro: function (u, a, b) { return "Tâches de l'unité " + u + " du " + a + " au " + b + "."; },
      weekly: "Chaque semaine", weeklyNext: function (d) { return "Prochaine fois : " + d + ", 19 h."; },
      off: "Congé", offText: "Aucune tâche cette période. Profitez-en!",
      done: "terminé", current: "en cours",
      binActions: "Vos sorties de bacs à 19 h",
      subTitle: "Ajouter à votre calendrier",
      subIntro: "Les tâches de votre unité et les rappels de 19 h (y compris votre recyclage), mis à jour chaque mois.",
      subApple: "S'abonner sur iPhone / Mac", subAppleHint: "Ouvre Calendrier d'Apple (un seul toucher).",
      subUrl: "Lien du calendrier", copy: "Copier le lien", copied: "Copié",
      subGoogle: "<b>Google Agenda</b> (sur un ordinateur) : Autres agendas <b>+</b> → <b>À partir de l'URL</b> → collez le lien. Il s'affiche ensuite aussi sur votre téléphone Android.",
      subOutlook: "<b>Outlook</b> : Ajouter un calendrier → <b>S'abonner à partir du web</b> → collez le lien.",
      subNote: "Google peut prendre jusqu'à une journée pour actualiser les agendas abonnés.",
      faqTitle: "Questions",
      faq: [
        ["Vous ne pouvez pas faire votre tâche?",
         "<p>Échangez avec une autre unité, puis notez l'échange sur le calendrier imprimé dans l'entrée. C'est tout.</p>"],
        ["Qui sort le recyclage?",
         "<p>Chaque unité a son propre bac de recyclage : <b>chaque unité</b> sort donc son bac le lundi à 19 h et le rentre le mardi à 19 h, chaque semaine. L'unité de service aux bacs s'occupe seulement des bacs communs de <b>compost</b> (bac brun) et d'<b>ordures</b>.</p>"],
        ["En quoi consiste chaque tâche?", "JOBS"],
        ["Je suis locataire. Est-ce que ça me concerne?",
         "<p>Oui. Chaque unité est responsable quand c'est son tour, que le travail soit fait par le locataire ou par le propriétaire. Locataires : voyez avec le propriétaire de votre unité. Les propriétaires restent responsables de s'assurer que la tâche de leur unité est faite.</p>"],
        ["Pourquoi faire tout ça?",
         "<p>Une entreprise s'occupe des gros travaux, comme le déneigement de l'entrée de garage ou la rénovation du sous-sol. Pour garder les coûts bas, c'est notre devoir collectif de nous occuper des petites choses. Tout le monde participe; sinon, une firme de gestion sera engagée, ce qui augmentera les coûts de chacun.</p>"],
        ["Quelles sont les règles de collecte?",
         "<ul><li>Les bacs peuvent être au bord de la rue seulement de <b>19 h la veille</b> de la collecte jusqu'à <b>7 h le jour de la collecte</b> (règlement de la ville).</li>" +
         "<li>Rentrez les bacs à <b>19 h le jour de la collecte</b> (règle de l'immeuble).</li>" +
         "<li>Compost et recyclage : chaque mardi. Ordures : un vendredi sur deux (Saint-Laurent, secteur 1).</li>" +
         "<li>Les feuilles vont dans des <b>sacs en papier ou des contenants réutilisables</b>, avec le compost. Pas de sacs de plastique, même compostables.</li>" +
         "<li>Les encombrants (1er vendredi du mois) ne font pas partie de la rotation : chaque propriétaire s'occupe des siens.</li>" +
         "<li>Les jours fériés peuvent déplacer une collecte. Consultez <a href=\"https://montreal.ca/info-collectes\" rel=\"noopener\">Info-Collectes</a> ou composez le 311.</li></ul>"],
        ["Où est le calendrier imprimé?", "PRINT"]
      ],
      majorWork: "Les gros travaux (déneigement de l'entrée de garage, rénovation du sous-sol…) sont faits par une entreprise et ne font pas partie de la rotation.",
      seasons: { all: "Toute l'année", fall: "Automne (oct.–nov.)", winter: "Hiver (déc.–mars)", spring_summer: "Printemps et été (avr.–sept.)" },
      printList: "Le calendrier du mois est affiché dans l'entrée. PDF :",
      foot: function (d) { return "Mis à jour le " + d + ". Une question ou un échange à noter? Écrivez dans le groupe WhatsApp de l'immeuble."; },
      loadError: "Impossible de charger le calendrier. Veuillez recharger la page."
    }
  };
  var LANGS = ["fr", "en"];
  var LANG_KEY = "poirier-lang", STORE_KEY = "poirier-unit";
  var lang, T;

  // ---------- helpers ----------
  var $ = function (id) { return document.getElementById(id); };
  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function parse(iso) { var p = iso.split("-"); return new Date(+p[0], p[1] - 1, +p[2]); }
  function iso(d) {
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }
  function addDays(d, n) { var x = new Date(d); x.setDate(x.getDate() + n); return x; }
  function fmt(d, opts) { return d.toLocaleDateString(T.locale, opts); }
  var fShort = function (d) { return fmt(d, { month: "short", day: "numeric" }); };
  var fDay = function (d) { return fmt(d, { weekday: "short", month: "short", day: "numeric" }); };
  var fMonth = function (d) { var s = fmt(d, { month: "long", year: "numeric" }); return s.charAt(0).toUpperCase() + s.slice(1); };
  function todayInMontreal(tz) {
    try {
      return new Intl.DateTimeFormat("en-CA", { timeZone: tz, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()).slice(0, 10);
    } catch (e) { return iso(new Date()); }
  }
  function store(k, v) {
    try { if (v === undefined) return localStorage.getItem(k); localStorage.setItem(k, v); } catch (e) { return null; }
  }
  // mix a hex colour with white (t = share of the colour)
  function tint(hex, t) {
    var n = parseInt(hex.slice(1), 16), r = n >> 16, g = (n >> 8) & 255, b = n & 255;
    var m = function (c) { return Math.round(c * t + 255 * (1 - t)); };
    return "rgb(" + m(r) + "," + m(g) + "," + m(b) + ")";
  }

  var S, today, months, monthIdx = 0, unit = null;

  // texts from schedule.json
  function jobName(j) { return S.job_info[j].name[lang]; }
  function jobShort(j) { return S.job_info[j].short[lang]; }
  function jobLong(j, season) { var t = S.job_info[j].long[lang]; return t[season] || t.all; }
  function actText(a, own) {
    var k = a.stream + "." + a.kind;
    return (own && S.own_text[lang][k]) || S.action_text[lang][k];
  }
  function noteText(a) { return a.note ? a.note[lang] : ""; }

  // unit chip; no unit = everyone (own recycling bin)
  function chip(u, label, cls, pre) {
    if (!u) return '<span class="chip all' + (cls ? " " + cls : "") + '">' + esc(T.all) + "</span>";
    var c = S.unit_colors[u] || ["#eee", "#333"];
    return '<span class="chip' + (cls ? " " + cls : "") + (u === unit ? " is-me" : "") + '" style="--bg:' + c[0] + ";--fg:" + c[1] + '">' +
      (pre ? '<span class="pre">' + esc(pre) + " </span>" : "") + esc(label || T.unit + " " + u) + "</span>";
  }
  function marker(stream) { return '<i class="mk mk-' + stream + '" aria-hidden="true"></i>'; }
  function periodsIn(first, last) {
    return S.periods.filter(function (p) { return p.start <= last && p.end >= first; });
  }
  function monthBounds(ym) {
    var f = parse(ym + "-01"), l = new Date(f.getFullYear(), f.getMonth() + 1, 0);
    return [f, l];
  }
  function pdfPath(ym) { return "print/" + ym + (lang === "en" ? "" : "-" + lang) + ".pdf"; }
  function actionLine(a, own) {
    return marker(a.stream) + " <b>" + T.at7 + "</b> " + esc(actText(a, own)) +
      (a.note ? ' <em class="note">(' + esc(noteText(a)) + ")</em>" : "");
  }

  // ---------- "right now" strip ----------
  function renderNow() {
    var el = $("now"), html = "", t = S.days[today], next = null;
    Object.keys(S.days).sort().some(function (k) {
      if (k >= today && S.days[k].actions.length) { next = k; return true; }
    });
    if (t && t.bins) html += '<div><span class="lbl">' + T.nowOnDuty + "</span> " + chip(t.bins) + "</div>";
    else if (today < S.periods[0].start) html += "<div>" + esc(T.nowStarts(fDay(parse(S.periods[0].start)))) + "</div>";
    if (next) {
      var head = next === today ? T.nowToday : T.nowNext + " · " + fDay(parse(next)) + ", " + T.at7long;
      html += '<div><span class="lbl">' + esc(head) + '</span><ul class="nowlist">' + S.days[next].actions.map(function (a) {
        return "<li>" + marker(a.stream) + " " + esc(actText(a)) + (a.note ? ' <em class="note">(' + esc(noteText(a)) + ")</em>" : "") + " " + chip(a.unit, a.unit) + "</li>";
      }).join("") + "</ul></div>";
    }
    el.innerHTML = html; el.hidden = !html;
  }

  // ---------- calendar ----------
  function renderMonth() {
    var ym = months[monthIdx], b = monthBounds(ym), first = b[0], last = b[1];
    var mName = fMonth(first);
    $("month-title").textContent = mName;
    $("prev").disabled = monthIdx === 0; $("next").disabled = monthIdx === months.length - 1;

    var start = addDays(first, -((first.getDay() + 6) % 7));
    var end = addDays(last, (7 - last.getDay()) % 7);
    var html = T.weekdays.map(function (w) { return '<div class="wd" role="columnheader">' + w + "</div>"; }).join("");
    for (var d = start; d <= end; d = addDays(d, 1)) {
      var k = iso(d), info = S.days[k], inm = d.getMonth() === first.getMonth();
      if (!inm) { html += '<div class="day out" aria-hidden="true"></div>'; continue; }
      var style = "", cls = "day";
      if (info && info.bins) {
        style = ' style="--tint:' + tint(S.unit_colors[info.bins][0], 0.6) + '"'; cls += " in-period";
        if (info.bins === unit) cls += " mine";
      } else cls += " pre";
      if (k === today) cls += " today";
      var label = fDay(d) + (info && info.bins ? ", " + T.bins + " " + info.bins : "");
      html += '<div class="' + cls + '"' + style + ' role="gridcell" aria-label="' + esc(label) + '">';
      html += '<div class="dh"><span class="dn">' + d.getDate() + "</span>";
      if (info && info.bins) html += chip(info.bins, info.bins, "tag", T.bins);
      html += "</div>";
      if (info && info.actions.length) {
        info.actions.forEach(function (a) {
          html += '<div class="act">' + marker(a.stream) + '<span><b>' + T.at7 + "</b> " + esc(actText(a)) +
            (a.note ? ' <em class="note">' + esc(noteText(a)) + "</em>" : "") + "</span></div>";
        });
        // phones: one line per kind, e.g. "●○ Out"
        ["out", "back"].forEach(function (kind) {
          var acts = info.actions.filter(function (a) { return a.kind === kind; });
          if (acts.length) html += '<div class="brief">' + acts.map(function (a) { return marker(a.stream); }).join("") +
            '<span class="lbl">' + T.short[kind] + (acts.some(function (a) { return a.note; }) ? "*" : "") + "</span></div>";
        });
      }
      html += "</div>";
    }
    $("grid").innerHTML = html;

    // agenda (phones)
    var rows = [];
    for (var x = new Date(first); x <= last; x = addDays(x, 1)) {
      var inf = S.days[iso(x)];
      if (inf) inf.actions.forEach(function (a) {
        rows.push('<li class="' + (iso(x) < today ? "past" : "") + (a.unit && a.unit === unit ? " mine" : "") + '"><span class="ad">' + esc(fDay(x)) + "</span>" +
          '<span class="at">' + actionLine(a) + "</span>" + chip(a.unit, a.unit) + "</li>");
      });
    }
    $("agenda").innerHTML = rows.length ? '<h3 class="h3">' + esc(T.agendaTitle(mName)) + "</h3><ul>" + rows.join("") + "</ul>" : "";

    // who does what
    $("who-title").textContent = T.whoTitle;
    var w = '<div class="wrow whead"><div>' + T.period + "</div>" + S.jobs.map(function (j) { return "<div>" + esc(jobName(j)) + "</div>"; }).join("") + "</div>";
    periodsIn(iso(first), iso(last)).forEach(function (p) {
      var cur = p.start <= today && today <= p.end;
      w += '<div class="wrow' + (cur ? " cur" : "") + '" style="--tint:' + tint(S.unit_colors[p.team[S.jobs[0]]][0], 0.6) + '">' +
        '<div class="wp">' + esc(fShort(parse(p.start)) + " – " + fShort(parse(p.end))) + (cur ? ' <span class="now-pill">' + T.current + "</span>" : "") + "</div>" +
        S.jobs.map(function (j) { return '<div class="wj"><span class="wl">' + esc(jobName(j)) + "</span>" + chip(p.team[j]) + "</div>"; }).join("") + "</div>";
    });
    $("who").innerHTML = w;

    var pl = $("print-link");
    pl.href = pdfPath(ym); pl.textContent = T.printLink(mName);
  }

  // ---------- my unit ----------
  function renderMine() {
    var sel = $("unit");
    $("mine-title").textContent = T.mineTitle;
    $("pick-label").textContent = T.pick;
    sel.innerHTML = '<option value="">' + T.pickNone + "</option>" + S.units.map(function (u) {
      return '<option value="' + u + '"' + (u === unit ? " selected" : "") + ">" + T.unit + " " + u + "</option>";
    }).join("");
    var body = $("mine-body");
    if (!unit) { body.innerHTML = ""; return; }
    var c = S.unit_colors[unit], accent = "--accent:" + c[1] + ";--soft:" + c[0];
    var html = '<p class="intro">' + esc(T.mineIntro(unit, fShort(parse(S.range.from)), fShort(parse(S.range.to)))) + "</p>";

    // weekly recycling: every unit, every week
    var nextRec = Object.keys(S.days).sort().filter(function (k) {
      return k >= today && S.days[k].actions.some(function (a) { return !a.unit && a.kind === "out"; });
    })[0];
    html += '<div class="weekly" style="' + accent + '"><div class="mj">' + marker("recycling") + " " + T.weekly + "</div>" +
      '<p class="mt">' + esc(S.everyone.long[lang]) + "</p>" +
      (nextRec ? '<p class="hint">' + esc(T.weeklyNext(fDay(parse(nextRec)))) + "</p>" : "") + "</div>";

    html += '<ol class="mine" style="' + accent + '">';
    S.periods.forEach(function (p) {
      var job = null;
      S.jobs.forEach(function (j) { if (p.team[j] === unit) job = j; });
      var state = p.end < today ? " past" : (p.start <= today ? " cur" : "");
      html += '<li class="mp' + state + (job ? "" : " off") + '"><div class="mh"><span class="md">' +
        esc(fShort(parse(p.start)) + " – " + fShort(parse(p.end))) + "</span>" +
        (state === " cur" ? ' <span class="now-pill">' + T.current + "</span>" : "") +
        (state === " past" ? ' <span class="done-pill">' + T.done + "</span>" : "") + "</div>";
      if (!job) { html += '<div class="mj">' + T.off + '</div><p class="mt">' + T.offText + "</p></li>"; return; }
      html += '<div class="mj">' + esc(jobName(job)) + ' <span class="ms">' + esc(jobShort(job)) + "</span></div>";
      html += '<p class="mt">' + esc(jobLong(job, p.season)) + "</p>";
      if (job === S.jobs[0]) {
        var acts = [];
        for (var d = parse(p.start); iso(d) <= p.end; d = addDays(d, 1)) {
          var inf = S.days[iso(d)];
          if (inf) inf.actions.forEach(function (a) {
            if (a.unit !== unit) return;
            acts.push('<li class="' + (iso(d) < today ? "past" : "") + '"><span class="ad">' + esc(fDay(d)) + '</span><span class="at">' + actionLine(a) + "</span></li>");
          });
        }
        if (acts.length) html += '<div class="acts"><div class="al">' + T.binActions + "</div><ul>" + acts.join("") + "</ul></div>";
      }
      html += "</li>";
    });
    html += "</ol>";

    var path = "ics/unit-" + unit + (lang === "en" ? "" : "-" + lang) + ".ics";
    var https = S.site_url.replace(/\/$/, "") + "/" + path;
    var webcal = https.replace(/^https?:/, "webcal:");
    html += '<div class="subscribe" style="' + accent + '"><h3 class="h3">' + T.subTitle + "</h3>" +
      "<p>" + T.subIntro + "</p>" +
      '<p><a class="btn" href="' + esc(webcal) + '">' + T.subApple + '</a></p><p class="hint">' + T.subAppleHint + "</p>" +
      '<label class="copyrow"><span>' + T.subUrl + '</span><span class="cr"><input id="ics-url" readonly value="' + esc(https) + '">' +
      '<button type="button" id="copy" class="btn ghost">' + T.copy + "</button></span></label>" +
      '<ul class="how"><li>' + T.subGoogle + "</li><li>" + T.subOutlook + "</li></ul>" +
      '<p class="hint">' + T.subNote + "</p></div>";
    body.innerHTML = html;
    $("copy").onclick = function () {
      var inp = $("ics-url"), btn = this;
      var ok = function () { btn.textContent = T.copied; setTimeout(function () { btn.textContent = T.copy; }, 1800); };
      if (navigator.clipboard) navigator.clipboard.writeText(inp.value).then(ok, function () { inp.select(); });
      else { inp.select(); try { document.execCommand("copy"); ok(); } catch (e) {} }
    };
  }

  // ---------- FAQ ----------
  function renderFaq() {
    $("faq-title").textContent = T.faqTitle;
    $("faq-body").innerHTML = T.faq.map(function (q) {
      var a = q[1];
      if (a === "JOBS") a = S.jobs.map(function (j) {
        var long = S.job_info[j].long[lang];
        return "<h4>" + esc(jobName(j)) + ' <span class="ms">' + esc(jobShort(j)) + "</span></h4><dl>" +
          Object.keys(long).map(function (s) { return "<dt>" + esc(T.seasons[s] || s) + "</dt><dd>" + esc(long[s]) + "</dd>"; }).join("") + "</dl>";
      }).join("") + "<h4>" + esc(S.everyone.name[lang]) + "</h4><dl><dt>" + esc(T.seasons.all) + "</dt><dd>" + esc(S.everyone.long[lang]) + "</dd></dl>" +
        '<p class="hint">' + T.majorWork + "</p>";
      if (a === "PRINT") a = "<p>" + T.printList + "</p><ul>" + months.map(function (m) {
        return '<li><a href="' + pdfPath(m) + '">' + esc(fMonth(parse(m + "-01"))) + "</a></li>";
      }).join("") + "</ul>";
      return "<details><summary>" + esc(q[0]) + '</summary><div class="ans">' + a + "</div></details>";
    }).join("");
  }

  function renderStatic() {
    document.documentElement.lang = lang;
    document.title = T.docTitle;
    document.querySelectorAll("[data-i18n]").forEach(function (el) { el.textContent = T[el.getAttribute("data-i18n")]; });
    document.querySelectorAll("#lang button").forEach(function (b) { b.setAttribute("aria-pressed", String(b.value === lang)); });
    $("prev").setAttribute("aria-label", T.prev); $("next").setAttribute("aria-label", T.next);
    $("rule").textContent = T.rule;
    $("legend").innerHTML = ["compost", "recycling", "garbage"].map(function (s) { return "<li>" + marker(s) + " " + T.legend[s] + "</li>"; }).join("") +
      '<li><span class="sw"></span> ' + T.legendBins + "</li>";
    $("foot").textContent = T.foot(fmt(new Date(S.generated), { year: "numeric", month: "long", day: "numeric" }));
  }

  function renderAll() { renderStatic(); renderNow(); renderMonth(); renderMine(); renderFaq(); }

  function setLang(l, save) {
    lang = LANGS.indexOf(l) >= 0 ? l : "fr"; T = STR[lang];
    document.documentElement.lang = lang;
    if (save) {
      store(LANG_KEY, lang);
      try { var u = new URL(location.href); u.searchParams.set("lang", lang); history.replaceState(null, "", u); } catch (e) {}
    }
  }
  function initialLang() {
    var q = new URLSearchParams(location.search).get("lang");
    if (LANGS.indexOf(q) >= 0) return q;
    var s = store(LANG_KEY);
    if (LANGS.indexOf(s) >= 0) return s;
    // French unless the browser clearly prefers English
    var nav = (navigator.languages && navigator.languages[0]) || navigator.language || "";
    return /^en/i.test(nav) ? "en" : "fr";
  }

  function init(data) {
    S = data; months = S.months; today = todayInMontreal(S.timezone);
    var cur = today.slice(0, 7);
    monthIdx = months.indexOf(cur);
    if (monthIdx < 0) monthIdx = cur > months[months.length - 1] ? months.length - 1 : 0;

    var q = new URLSearchParams(location.search).get("unit");
    unit = (q && S.units.indexOf(q) >= 0) ? q : store(STORE_KEY);
    if (S.units.indexOf(unit) < 0) unit = null;

    renderAll();
    $("prev").onclick = function () { if (monthIdx > 0) { monthIdx--; renderMonth(); } };
    $("next").onclick = function () { if (monthIdx < months.length - 1) { monthIdx++; renderMonth(); } };
    $("unit").onchange = function () { unit = this.value || null; store(STORE_KEY, unit || ""); renderNow(); renderMonth(); renderMine(); };
  }

  setLang(initialLang(), false);
  document.querySelectorAll("#lang button").forEach(function (b) {
    b.onclick = function () { if (b.value !== lang) { setLang(b.value, true); if (S) renderAll(); } };
  });
  fetch("schedule.json", { cache: "no-cache" })
    .then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); })
    .then(init)
    .catch(function () { $("month-title").textContent = T.loadError; });
})();
