/* 2675 boul. Poirier: building duty calendar.
   Reads schedule.json (generated by tools/generate.py). No dependencies. */
(function () {
  "use strict";

  // ---------- strings (add a "fr" block to translate) ----------
  var LANG = "en";
  var STR = {
    en: {
      locale: "en-CA",
      title: "2675 boul. Poirier",
      subtitle: "Building duty calendar · 4 jobs, 4 units, every 2 weeks · 2 units off",
      prev: "Previous month", next: "Next month",
      rule: "Bins go to the curb at 7pm the evening before pickup and come back in at 7pm on pickup day.",
      legendRC: "Recycling & Compost (pickup every Tuesday)",
      legendG: "Garbage (pickup every other Friday)",
      legendBins: "Day colour = unit on bins duty",
      weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      bins: "Bins", unit: "Unit", at7: "7pm:",
      short: { out: "Out", back: "Back" },
      agendaTitle: function (m) { return "Bin actions in " + m; },
      whoTitle: "Who does what",
      period: "Period",
      printLink: function (m) { return "Printable calendar for " + m + " (PDF)"; },
      nowToday: "Today", nowTonight: "Tonight at 7pm",
      nowNext: "Next bin action",
      nowOnDuty: "On bins duty now",
      nowStarts: function (d) { return "The rotation starts on " + d + "."; },
      mineTitle: "My unit",
      pick: "Choose your unit",
      pickNone: "Select…",
      mineIntro: function (u, a, b) { return "Unit " + u + "'s jobs from " + a + " to " + b + "."; },
      off: "Off", offText: "No job this period. Enjoy!",
      done: "done", current: "now",
      binActions: "Your 7pm bin actions",
      confirm: "confirm date",
      subTitle: "Add to your calendar",
      subIntro: "Your unit's jobs and 7pm bin reminders, updated every month.",
      subApple: "Subscribe on iPhone / Mac",
      subAppleHint: "Opens Apple Calendar (one tap).",
      subUrl: "Calendar link",
      copy: "Copy link", copied: "Copied",
      subGoogle: "<b>Google Calendar</b> (on a computer): Other calendars <b>+</b> → <b>From URL</b> → paste the link. It then shows on your Android phone too.",
      subOutlook: "<b>Outlook</b>: Add calendar → <b>Subscribe from web</b> → paste the link.",
      subNote: "Google may take up to a day to refresh subscribed calendars.",
      faqTitle: "Questions",
      faq: [
        ["Can't do your job?",
         "<p>Swap with another unit, then write the swap on the printed calendar in the entrance. That's it.</p>"],
        ["What exactly does each job involve?", "JOBS"],
        ["I'm a tenant. Does this apply to me?",
         "<p>Yes. Every unit is responsible when it's assigned, whether the work is done by the tenant or the owner. Tenants: check with your unit's owner. Owners stay responsible for making sure their unit's job gets done.</p>"],
        ["Why do we need to do all this?",
         "<p>We have a company for major work such as snow plowing the driveway or renovating the basement. To keep costs down, it's our collective duty to take care of the small things. Everyone participates; otherwise a management firm will be brought in, and that raises everyone's costs.</p>"],
        ["What are the collection rules?",
         "<ul><li>Bins may only be at the curb from <b>7pm the evening before</b> pickup to <b>7am on pickup day</b> (city rule).</li>" +
         "<li>Bring bins back in at <b>7pm on pickup day</b> (building rule).</li>" +
         "<li>Recycling & compost: every Tuesday. Garbage: every other Friday (Saint-Laurent, sector 1).</li>" +
         "<li>Leaves go in <b>paper bags or reusable containers</b>, out with the compost. No plastic bags, even compostable ones.</li>" +
         "<li>Large items (1st Friday of the month) aren't part of the rotation: each owner handles their own.</li>" +
         "<li>Holidays can move a pickup. Check <a href=\"https://montreal.ca/info-collectes\" rel=\"noopener\">Info-Collecte</a> or call 311.</li></ul>"],
        ["Where's the printed calendar?", "PRINT"]
      ],
      seasons: { all: "All year", fall: "Fall (Oct–Nov)", winter: "Winter (Dec–Mar)", spring_summer: "Spring & summer (Apr–Sep)" },
      printList: "This month's printout is posted in the entrance. PDFs:",
      foot: function (d) { return "Updated " + d + ". Questions or a swap to record? Post in the building WhatsApp group."; },
      loadError: "Couldn't load the calendar. Please reload the page."
    }
  };
  var T = STR[LANG];
  var STORE_KEY = "poirier-unit";

  // ---------- helpers ----------
  var $ = function (id) { return document.getElementById(id); };
  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function parse(iso) { var p = iso.split("-"); return new Date(+p[0], p[1] - 1, +p[2]); }
  function iso(d) {
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }
  function addDays(d, n) { var x = new Date(d); x.setDate(x.getDate() + n); return x; }
  function fmt(d, opts) { return d.toLocaleDateString(T.locale, opts); }
  var fShort = function (d) { return fmt(d, { month: "short", day: "numeric" }); };
  var fDay = function (d) { return fmt(d, { weekday: "short", month: "short", day: "numeric" }); };
  var fMonth = function (d) { return fmt(d, { month: "long", year: "numeric" }); };
  function todayInMontreal(tz) {
    try {
      var p = new Intl.DateTimeFormat("en-CA", { timeZone: tz, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
      return p.slice(0, 10);
    } catch (e) { return iso(new Date()); }
  }
  function store(k, v) {
    try { if (v === undefined) return localStorage.getItem(k); localStorage.setItem(k, v); } catch (e) { return null; }
  }
  // mix a hex colour with white (t = share of the colour)
  function tint(hex, t) {
    var n = parseInt(hex.slice(1), 16), r = n >> 16, g = (n >> 8) & 255, b = n & 255;
    var m = function (c) { return Math.round(c * t + 255 * (1 - t)); };
    return "rgb(" + m(r) + "," + m(g) + "," + m(b) + ")";
  }

  var S, today, months, monthIdx = 0, unit = null;

  function chip(u, label, cls, pre) {
    var c = S.unit_colors[u] || ["#eee", "#333"];
    return '<span class="chip' + (cls ? " " + cls : "") + (u === unit ? " is-me" : "") + '" style="--bg:' + c[0] + ";--fg:" + c[1] + '">' +
      (pre ? '<span class="pre">' + esc(pre) + " </span>" : "") + esc(label || T.unit + " " + u) + "</span>";
  }
  function marker(stream) { return '<i class="mk mk-' + (stream === "garbage" ? "g" : "rc") + '" aria-hidden="true"></i>'; }
  function periodsIn(first, last) {
    return S.periods.filter(function (p) { return p.start <= last && p.end >= first; });
  }
  function monthBounds(ym) {
    var f = parse(ym + "-01"), l = new Date(f.getFullYear(), f.getMonth() + 1, 0);
    return [f, l];
  }

  // ---------- "right now" strip ----------
  function renderNow() {
    var el = $("now"), html = "";
    var t = S.days[today];
    var next = null;
    Object.keys(S.days).sort().some(function (k) {
      if (k >= today && S.days[k].actions.length) { next = k; return true; }
    });
    if (t && t.bins) html += '<div><span class="lbl">' + T.nowOnDuty + "</span> " + chip(t.bins) + "</div>";
    else if (today < S.periods[0].start) html += "<div>" + esc(T.nowStarts(fDay(parse(S.periods[0].start)))) + "</div>";
    if (next) {
      var acts = S.days[next].actions;
      var when = next === today ? T.nowTonight : fDay(parse(next)) + ", 7pm";
      html += '<div><span class="lbl">' + (next === today ? T.nowToday : T.nowNext) + "</span> " +
        esc(when) + ": " + acts.map(function (a) { return marker(a.stream) + " " + esc(a.text) + " " + chip(a.unit, a.unit); }).join(" · ") + "</div>";
    }
    el.innerHTML = html; el.hidden = !html;
  }

  // ---------- calendar ----------
  function renderMonth() {
    var ym = months[monthIdx], b = monthBounds(ym), first = b[0], last = b[1];
    var mName = fMonth(first);
    $("month-title").textContent = mName;
    $("prev").disabled = monthIdx === 0; $("next").disabled = monthIdx === months.length - 1;

    var start = addDays(first, -((first.getDay() + 6) % 7));
    var end = addDays(last, (7 - last.getDay()) % 7);
    var html = T.weekdays.map(function (w) { return '<div class="wd" role="columnheader">' + w + "</div>"; }).join("");
    for (var d = start; d <= end; d = addDays(d, 1)) {
      var k = iso(d), info = S.days[k], inm = d.getMonth() === first.getMonth();
      if (!inm) { html += '<div class="day out" aria-hidden="true"></div>'; continue; }
      var style = "", cls = "day";
      if (info && info.bins) {
        var c = S.unit_colors[info.bins];
        style = ' style="--tint:' + tint(c[0], 0.6) + '"'; cls += " in-period";
        if (info.bins === unit) cls += " mine";
      } else cls += " pre";
      if (k === today) cls += " today";
      var label = fDay(d) + (info && info.bins ? ", " + T.bins + " " + info.bins : "");
      html += '<div class="' + cls + '"' + style + ' role="gridcell" aria-label="' + esc(label) + '">';
      html += '<div class="dh"><span class="dn">' + d.getDate() + "</span>";
      if (info && info.bins) html += chip(info.bins, info.bins, "tag", T.bins);
      html += "</div>";
      if (info) info.actions.forEach(function (a) {
        html += '<div class="act">' + marker(a.stream) + '<span class="full"><b>' + T.at7 + "</b> " + esc(a.text) +
          (a.note ? ' <em class="note">' + esc(a.note) + "</em>" : "") + "</span>" +
          '<span class="brief">' + T.short[a.kind] + (a.note ? "*" : "") + "</span></div>";
      });
      html += "</div>";
    }
    $("grid").innerHTML = html;

    // compact agenda for phones
    var rows = [];
    for (var x = new Date(first); x <= last; x = addDays(x, 1)) {
      var inf = S.days[iso(x)];
      if (inf) inf.actions.forEach(function (a) {
        rows.push('<li class="' + (iso(x) < today ? "past" : "") + (a.unit === unit ? " mine" : "") + '"><span class="ad">' + esc(fDay(x)) + "</span>" +
          '<span class="at">' + marker(a.stream) + " <b>" + T.at7 + "</b> " + esc(a.text) +
          (a.note ? ' <em class="note">(' + esc(a.note) + ")</em>" : "") + "</span>" + chip(a.unit, a.unit) + "</li>");
      });
    }
    $("agenda").innerHTML = rows.length ? "<h3 class=\"h3\">" + esc(T.agendaTitle(mName)) + "</h3><ul>" + rows.join("") + "</ul>" : "";

    // who does what
    $("who-title").textContent = T.whoTitle;
    var ps = periodsIn(iso(first), iso(last));
    var w = '<div class="wrow whead"><div>' + T.period + "</div>" + S.jobs.map(function (j) { return "<div>" + esc(j) + "</div>"; }).join("") + "</div>";
    ps.forEach(function (p) {
      var cur = p.start <= today && today <= p.end;
      w += '<div class="wrow' + (cur ? " cur" : "") + '" style="--tint:' + tint(S.unit_colors[p.team[S.jobs[0]]][0], 0.6) + '">' +
        '<div class="wp">' + esc(fShort(parse(p.start)) + " – " + fShort(parse(p.end))) + (cur ? ' <span class="now-pill">' + T.current + "</span>" : "") + "</div>" +
        S.jobs.map(function (j) { return '<div class="wj"><span class="wl">' + esc(j) + "</span>" + chip(p.team[j]) + "</div>"; }).join("") + "</div>";
    });
    $("who").innerHTML = w;

    var pl = $("print-link");
    pl.href = "print/" + ym + ".pdf"; pl.textContent = T.printLink(mName);
  }

  // ---------- my unit ----------
  function renderMine() {
    var sel = $("unit");
    $("mine-title").textContent = T.mineTitle;
    $("pick-label").textContent = T.pick;
    sel.innerHTML = '<option value="">' + T.pickNone + "</option>" + S.units.map(function (u) {
      return '<option value="' + u + '"' + (u === unit ? " selected" : "") + ">" + T.unit + " " + u + "</option>";
    }).join("");
    var body = $("mine-body");
    if (!unit) { body.innerHTML = ""; return; }
    var c = S.unit_colors[unit];
    var html = '<p class="intro">' + esc(T.mineIntro(unit, fShort(parse(S.range.from)), fShort(parse(S.range.to)))) + "</p>";
    html += '<ol class="mine" style="--accent:' + c[1] + ";--soft:" + c[0] + '">';
    S.periods.forEach(function (p) {
      var job = null;
      S.jobs.forEach(function (j) { if (p.team[j] === unit) job = j; });
      var state = p.end < today ? " past" : (p.start <= today ? " cur" : "");
      html += '<li class="mp' + state + (job ? "" : " off") + '"><div class="mh"><span class="md">' +
        esc(fShort(parse(p.start)) + " – " + fShort(parse(p.end))) + "</span>" +
        (state === " cur" ? ' <span class="now-pill">' + T.current + "</span>" : "") +
        (state === " past" ? ' <span class="done-pill">' + T.done + "</span>" : "") + "</div>";
      if (!job) { html += '<div class="mj">' + T.off + '</div><p class="mt">' + T.offText + "</p></li>"; return; }
      html += '<div class="mj">' + esc(job) + ' <span class="ms">' + esc(S.job_info[job].short) + "</span></div>";
      html += '<p class="mt">' + esc(p.tasks[job]) + "</p>";
      if (job === S.jobs[0]) {
        var acts = [];
        for (var d = parse(p.start); iso(d) <= p.end; d = addDays(d, 1)) {
          var inf = S.days[iso(d)];
          if (inf) inf.actions.forEach(function (a) {
            if (a.unit !== unit) return;
            acts.push('<li class="' + (iso(d) < today ? "past" : "") + '"><span class="ad">' + esc(fDay(d)) + '</span><span class="at">' + marker(a.stream) +
              " <b>" + T.at7 + "</b> " + esc(a.text) + (a.note ? ' <em class="note">(' + esc(T.confirm) + ": " + esc(a.note) + ")</em>" : "") + "</span></li>");
          });
        }
        if (acts.length) html += '<div class="acts"><div class="al">' + T.binActions + "</div><ul>" + acts.join("") + "</ul></div>";
      }
      html += "</li>";
    });
    html += "</ol>";

    var path = "ics/unit-" + unit + ".ics";
    var https = S.site_url.replace(/\/$/, "") + "/" + path;
    var webcal = https.replace(/^https?:/, "webcal:");
    html += '<div class="subscribe" style="--accent:' + c[1] + ";--soft:" + c[0] + '"><h3 class="h3">' + T.subTitle + "</h3>" +
      "<p>" + T.subIntro + "</p>" +
      '<p><a class="btn" href="' + esc(webcal) + '">' + T.subApple + "</a></p><p class=\"hint\">" + T.subAppleHint + "</p>" +
      '<label class="copyrow"><span>' + T.subUrl + '</span><span class="cr"><input id="ics-url" readonly value="' + esc(https) + '">' +
      '<button type="button" id="copy" class="btn ghost">' + T.copy + "</button></span></label>" +
      "<ul class=\"how\"><li>" + T.subGoogle + "</li><li>" + T.subOutlook + "</li></ul>" +
      '<p class="hint">' + T.subNote + "</p></div>";
    body.innerHTML = html;
    $("copy").onclick = function () {
      var inp = $("ics-url"), btn = this;
      var ok = function () { btn.textContent = T.copied; setTimeout(function () { btn.textContent = T.copy; }, 1800); };
      if (navigator.clipboard) navigator.clipboard.writeText(inp.value).then(ok, function () { inp.select(); });
      else { inp.select(); try { document.execCommand("copy"); ok(); } catch (e) {} }
    };
  }

  // ---------- FAQ ----------
  function renderFaq() {
    $("faq-title").textContent = T.faqTitle;
    var html = T.faq.map(function (q) {
      var a = q[1];
      if (a === "JOBS") a = S.jobs.map(function (j) {
        var info = S.job_info[j], seasons = Object.keys(info.long);
        return "<h4>" + esc(j) + ' <span class="ms">' + esc(info.short) + "</span></h4><dl>" +
          seasons.map(function (s) { return "<dt>" + esc(T.seasons[s] || s) + "</dt><dd>" + esc(info.long[s]) + "</dd>"; }).join("") + "</dl>";
      }).join("") + "<p class=\"hint\">Major work (snow plowing the driveway, basement renovation…) is done by a hired company and isn't part of the rotation.</p>";
      if (a === "PRINT") a = "<p>" + T.printList + "</p><ul>" + months.map(function (m) {
        return '<li><a href="print/' + m + '.pdf">' + esc(fMonth(parse(m + "-01"))) + "</a></li>";
      }).join("") + "</ul>";
      return "<details><summary>" + esc(q[0]) + '</summary><div class="ans">' + a + "</div></details>";
    }).join("");
    $("faq-body").innerHTML = html;
  }

  function renderStatic() {
    document.documentElement.lang = LANG;
    document.querySelectorAll("[data-i18n]").forEach(function (el) { el.textContent = T[el.getAttribute("data-i18n")]; });
    $("prev").setAttribute("aria-label", T.prev); $("next").setAttribute("aria-label", T.next);
    $("rule").textContent = T.rule;
    $("legend").innerHTML = "<li>" + marker("recycling_compost") + " " + T.legendRC + "</li><li>" + marker("garbage") + " " + T.legendG +
      '</li><li><span class="sw"></span> ' + T.legendBins + "</li>";
    $("foot").textContent = T.foot(fmt(new Date(S.generated), { year: "numeric", month: "long", day: "numeric" }));
  }

  function renderAll() { renderNow(); renderMonth(); renderMine(); }

  function init(data) {
    S = data; months = S.months; today = todayInMontreal(S.timezone);
    var cur = today.slice(0, 7);
    monthIdx = Math.max(0, months.indexOf(cur));
    if (months.indexOf(cur) < 0 && cur > months[months.length - 1]) monthIdx = months.length - 1;

    var q = new URLSearchParams(location.search).get("unit");
    unit = (q && S.units.indexOf(q) >= 0) ? q : store(STORE_KEY);
    if (S.units.indexOf(unit) < 0) unit = null;

    renderStatic(); renderFaq(); renderAll();
    $("prev").onclick = function () { if (monthIdx > 0) { monthIdx--; renderMonth(); } };
    $("next").onclick = function () { if (monthIdx < months.length - 1) { monthIdx++; renderMonth(); } };
    $("unit").onchange = function () {
      unit = this.value || null; store(STORE_KEY, unit || "");
      renderAll();
    };
  }

  fetch("schedule.json", { cache: "no-cache" })
    .then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); })
    .then(init)
    .catch(function () { $("month-title").textContent = T.loadError; });
})();
